### ISSUE TITLE
Investigate gcloud

### ISSUE THREAD

**Issue by alenkacz** [alenkacz/cert-manager-verifier#3]
Does not work on GKE

This is the output
```
Waiting for deployments in namespace cert-manager:
Error: unable to get kubernetes client: no Auth Provider found for name "gcp"
```

**Comment by jujoramos** [comment]
Adding `_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"` to the list of imported packages should fix this.

**Comment by beyondbill** [comment]
I ran into the same issue.

@jujoramos Is there a reason the PR above closed without merging?

**Comment by jujoramos** [comment]
@beyondbill : I didn't get a response over 5 months and I don't have merge privileges so I've closed it 🤷‍♂️

**Comment by alenkacz** [comment]
sorry, my second kid got born and I lost all my free time 😅 could you reopen? I'll take a look later this week

**Comment by jujoramos** [comment]
I'll reopen it, no worries. And congratulations for the baby! 🍾
