### ISSUE TITLE
Would it be possible to bundle a new release?

### ISSUE THREAD

**Issue by AndrewSav** [alenkacz/cert-manager-verifier#6]
It seems that 0.2.0 returns zero code on failure which conflicts with what stated in readme. Would it be possible to bundle a new release that fixes this in a recent commit? Many thanks.

**Comment by AndrewSav** [comment]
Looking at the issues history it seems that intention was to fix the exit code in  0.2.0, so it seems to be a mix up. In particular this binary from the releases page: https://github.com/alenkacz/cert-manager-verifier/releases/download/v0.2.0/cert-manager-verifier_0.2.0_Linux_x86_64.tar.gz does NOT contain the fix.

**Comment by AndrewSav** [comment]
Also to make this more transparent in future a suggestion would be to have a version switch that can display the current version of the tool.

**Comment by alenkacz** [comment]
Oooh, thanks for reporting this. I'll do a release later today!

**Comment by alenkacz** [comment]
Aaand it's released - I removed the broken 0.2.0 and released the proper one with the fixes. Enjoy!
